[tool.poetry]
name = "clunk"
version = "0.1.0"
description = "A command-line interface for a C++ program"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"

[tool.poetry.scripts]
clunk = "clunk.cli:main"

